-- Migration 014: Add PV (Points Value) foundation columns and settings
-- Phase 1 of PV-centered architecture adoption.
-- No commission logic changes; existing bonuses remain untouched.

-- ─── Package PV rate ───────────────────────────────────────────────────────
ALTER TABLE packages
  ADD COLUMN package_pv_rate DECIMAL(5,2) NOT NULL DEFAULT 100.00
    COMMENT 'Percentage of entry fee that becomes package PV' AFTER entry_fee;

-- ─── User PV tracking ──────────────────────────────────────────────────────
ALTER TABLE users
  ADD COLUMN left_pv          DECIMAL(14,2) NOT NULL DEFAULT 0.00 COMMENT 'Accumulated PV on left binary leg'    AFTER right_count,
  ADD COLUMN right_pv         DECIMAL(14,2) NOT NULL DEFAULT 0.00 COMMENT 'Accumulated PV on right binary leg'   AFTER left_pv,
  ADD COLUMN flushed_pv       DECIMAL(14,2) NOT NULL DEFAULT 0.00 COMMENT 'PV that has been flushed in pairing'  AFTER right_pv,
  ADD COLUMN personal_pv      DECIMAL(14,2) NOT NULL DEFAULT 0.00 COMMENT 'Personal sales PV (package + product)' AFTER flushed_pv,
  ADD COLUMN group_pv         DECIMAL(14,2) NOT NULL DEFAULT 0.00 COMMENT 'Group sales PV from downline'         AFTER personal_pv,
  ADD COLUMN total_package_pv DECIMAL(14,2) NOT NULL DEFAULT 0.00 COMMENT 'Total package PV generated by member' AFTER group_pv;

-- ─── System settings ───────────────────────────────────────────────────────
INSERT INTO settings (`key_name`, `value`) VALUES
  ('pv_per_peso_rate', '1000.0000')
ON DUPLICATE KEY UPDATE value = value;
